#!/usr/bin/env perl

use strict;
use warnings;
use PDL;
use PDL::AutoLoader;
use Getopt::Long;

sub usage()
{
    print "Unknown option: @_\n" if ( @_ );
    print "usage: swamis [--file <file>] [--help|-?]\n";
    exit;
}

my $reset = 0;
my $tmpdir;
my $numFilesKept = 50;
my $file;
my $thrDetHi = 300.0;
my $thrDetLo = 100.0;
my $scaleMask = 0xff;
my $minSize = 2;
my $feaDist = 4;
my $feaMethod = 'clump';
my $maxEta = 60.0;
my $timeAtMax = 2;
my $senseGrowth = 0;
my $thrGrowth;
my $timeGrowth;
my $thrFlLo;
my $thrFlHi;
my $minVol = 0;
my $minLife = 4;
my $minMaxSize = 4;
my $nBack = 3;

my $help;

usage() if (! GetOptions('reset' => \$reset,
                         'tmpdir=s' => \$tmpdir,
                         'numFilesKept=i' => \$tmpdir,
                         'file|f=s' => \$file,
                         'thrDetHi=f' => \$thrDetHi,
                         'thrDetLo=f' => \$thrDetLo,
                         'scaleMask=i' => \$scaleMask,
                         'minSize=i' => \$minSize,
                         'feaDist=i' => \$feaDist,
                         'feaMethod=s' => \$feaMethod,
                         'maxEta=f' => \$maxEta,
                         'timeAtMax=i' => \$timeAtMax,
                         'senseGrowth' => \$senseGrowth,
                         'thrGrowth=f' => \$thrGrowth,
                         'timeGrowth=i' => \$timeGrowth,
                         'thrFlLo=f' => \$thrFlLo,
                         'thrFlHi=f' => \$thrFlHi,
                         'minVol=i' => \$minVol,
                         'minLife=i' => \$minLife,
                         'minMaxSize=i' => \$minMaxSize,
                         'nBack=i' => \$nBack,
                         'help|?' => \$help)
            or defined $help);

if (!defined $tmpdir)
{
    print "Must define tmpdir\n";
    exit 1;
}
    
if ($reset)
{
    ### Create the directories
    `rm -rf $tmpdir/00-data; mkdir $tmpdir/00-data`;
    `rm -rf $tmpdir/01-mask; mkdir $tmpdir/01-mask`;
    `rm -rf $tmpdir/02-id; mkdir $tmpdir/02-id`;
    `rm -rf $tmpdir/03-assoc; mkdir $tmpdir/03-assoc`;
    `rm -rf $tmpdir/04-tab; mkdir $tmpdir/04-tab`;
    
    ### Initialize the SQLite databases
    `rm -f $tmpdir/swamis.sdb`;

    my $thresh = [$thrDetLo, $thrDetHi];
    purge({tmpdir=>$tmpdir,
           thresh=>$thresh,
           method=>$feaMethod,
           scaleMask=>$scaleMask,
           feaDist=>$feaDist,
           maxEta=>$maxEta,
           timeAtMax=>$timeAtMax,
           senseGrowth=>$senseGrowth,
           thrGrowth=>$thrGrowth,
           timeGrowth=>$timeGrowth,
           thrFlLo=>$thrFlLo,
           thrFlHi=>$thrFlHi,
           min_sz=>$minSize,
           v_min=>$minVol,
           t_min=>$minLife,
           sz_min=>$minMaxSize,
           n_back=>$nBack});
}
else
{
    if (!defined $file)
    {
        print "Filename missing\n";
        exit 1;
    }

    `cp $file $tmpdir/00-data`;

    swamis({tmpdir=>$tmpdir});
}
